const actions = {
	HELLO: [
		"czesc",
		"cześć",
		"cześc",
		"czesć",
		"witaj",
		"hi",
		"hello",
		"hello there",
		"hey",
		"hej",
		"siema",
		"siemano",
		"siemanko",
		"gitara siema",
	],
	DATE: [
		"data",
		"podaj date",
		"podaj datę",
		"jaki mamy dzień",
		"jaki mamy dzien",
	],
	HELP: ["help", "pomoc"],
	CATS: ["pokaż kota", "kot", "pokaz kota"],
	DOGS: ["pokaż psa", "pies", "pokaz psa"],
	WEATHER: [
		"pogoda",
		"pokaż pogodę",
		"pokaz pogode",
		"pokaż pogode",
		"pokaz pogodę",
	],
	LS: ["ls"],
	MATRIX: ["macierz"],
	ZDITM: ["zditm"],
	ZTM: ["ztm"],
	LOVE: ["kocham cię", "kocham cie", "i love you", "愛している"],
	JOKE: ["opowiedz żart", "opowiedz zart", "joke", "zart", "żart"],
};

module.exports = actions;
